server:
  port: 8080
  
spring:
  application:
    name: UserSystem
  datasource:
    url: jdbc:mysql://localhost:3306/usersystem
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8090/eureka
       
    
    
    
    